### ISSUE TITLE
quick start tutorial: bug when importing cellex module

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLEX#5] opened 2019-10-29 15:40 UTC
### code entered

```
import numpy as np # needed for formatting data for this tutorial
import pandas as pd # needed for formatting data for this tutorial
import CELLEX.cellex as cellex # needed when importing directly from this repo
```
### Expected behaviour

load modules

### Actual behaviour

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-6f0745f9fe8a> in <module>
      1 import numpy as np # needed for formatting data for this tutorial
      2 import pandas as pd # needed for formatting data for this tutorial
----> 3 import CELLEX.cellex as cellex # needed when importing directly from this repo

/nfsdata/projects/jonatan/tools/sc-genetics/CELLEX/cellex/__init__.py in <module>
     15 from . import preprocessing
     16 from . import utils
---> 17 from .esobject import ESObject
     18 from .summarydata import SummaryData

/nfsdata/projects/jonatan/tools/sc-genetics/CELLEX/cellex/esobject.py in <module>
      8 from . import metrics
      9 from . import utils
---> 10 from cellex import ES_METRICS
     11 
     12 

ModuleNotFoundError: No module named 'cellex'

```

**Comment by Satannius** [comment] 2019-10-29 15:51
Hi and thanks for submitting this issue!

The tutorial should be updated to recommend installing cellex in your env via pip and then use `import cellex` to import cellex.

`import CELLEX.cellex` was intended for importing the pre-pip release of cellex.

Fixing this error by changing `from cellex import ES_METRICS`to `from CELLEX.cellex import ES_METRICS` would probably break the pip package.

Can you make the tutorial work with the cellex package installed from pip?

Alternatively you might build and install cellex into your env from a cloned repo using `python setup.py install`.

Let me know if this solves the issue 🙂

**Comment by Satannius** [comment] 2019-11-10 11:34
Fixed by @pvtodorov 's PR in CELLEX/develop

**Closed by Satannius** 2019-11-10 11:34 UTC
Labels: documentation
